# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest_cov_60_percent.yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_TOTAL: 60

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: pytester-cov
        id: pytester-cov
        uses: alexanderdamiani/pytester-cov@v1.2.0
        with:
          pytest-root-dir: './example/source'
          pytest-tests-dir: './example/tests'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}

      - name: Coverage single fail - new issue
        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: workflow-failed
          body: ${{ steps.pytester-cov.outputs.output-table }}

      - name: Coverage single fail - exit
        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
        run: |
          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
          exit 1

      - name: Coverage total fail - new issue
        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: workflow-failed
          body: ${{ steps.pytester-cov.outputs.output-table }}

      - name: Coverage total fail - exit
        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
        run: |
          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
          exit 1

